# Generated by Django 4.2.1 on 2023-05-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Updator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='author',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='content',
            name='confirmation_use_information_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='disclosure_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='phonenum',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='contentType',
            field=models.CharField(choices=[('영상', 'Video'), ('사진', 'Image')], max_length=10),
        ),
        migrations.AlterField(
            model_name='content',
            name='email',
            field=models.EmailField(blank=True, max_length=128, verbose_name='사용자 이메일'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
