# Generated by Django 4.2.1 on 2023-06-01 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Updator', '0002_content_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='content',
            name='phonenum',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
